# Solutions Ninja Training 4

* [Task 1](#n4t1)
* [Task 2](#n4t2)
* [Task 3](#n4t3)

## Task 1 <a name="n4t1"></a>

Conduct some research on the bernoulli and binomial distribution.

**Solution :**

The Bernoulli distribution with parameter $p$ is a discrete probability distribution of a random variable which takes the value 1 with probability $p$ and the value 0 with probability $1 − p$, that is, the probability distribution of any single experiment that asks a yes or no question.

If one sets $p =1/2$, one would have a model for a coin toss. 

* mean: $\mu = p$.
* variance: $\sigma^2 = p(1-p)$.

The binomial distribution with parameters $n$ and $p$ is the discrete probability distribution of the number of successes in a sequence of $n$ independent experiments, each asking a yes or no question. 

So if one sets $p= 1/2$ the binomial distribution models $n$ coin tosses.

* mean: $\mu = np$.
* variance: $\sigma^2 = np(1-p)$.

## Task 2 <a name="n4t2"></a>

Write a function that returns the probability that 4 out of 10 tosses of a coin are heads.
This is actually a very hard question so make sure you did the research from Task 1.

**Solution :**

From our research above we know that we should use a binomial distribution with parameters $n=10$ and $p=1/2$.

My solution will be more general than what is required. The function we will construct will be the pmf of a binomial distribution. Then once we have this we will evaluate it at 4.

The pmf of a binomial distribution is

$$ p(x) = {n\choose k}p^x(1-p)^{n-x} = \frac{n!}{x!(n -x)!}p^x(1-p)^{n-x} $$

In [17]:
import numpy as np
n = 10
p = 1/2
def binomial_pmf(x):
    return np.math.factorial(n)/(np.math.factorial(x)*np.math.factorial(n - x))*p**(x)*(1-p)**(n-x)

In [27]:
binomial_pmf(4)

0.205078125

The is an added bonus.

If you were asked what is the probabity you get at most 4 heads. You would be required to compute

$$\mathbb{P}(X \leq 4) =\mathbb{P}(X = 0)+\mathbb{P}(X = 1)+\mathbb{P}(X = 2)+\mathbb{P}(X = 3)+\mathbb{P}(X = 4)$$

Thus we would have

In [28]:
binomial_pmf(0)+ binomial_pmf(1)+ binomial_pmf(2)+ binomial_pmf(3)+ binomial_pmf(4) 

0.376953125

## Task 3 <a name="n4t3"></a>

Starting with the array below as an input, write a function that changes every even element of the array to zero.

In [29]:
input_array = np.arange(3,15)
print(input_array)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


**Solution :**

In [44]:
input_array = np.arange(3,15)
def change_even_to_zero(x):
    for i in range(len(x)):
        if x[i]%2==0:
            x[i]=0
        else: pass   
    return x
change_even_to_zero(input_array)

array([ 3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])

In [40]:
input_array = np.arange(3,15)
def change_even_to_zero_advanced(x):
    x[x%2==0]=0
    return x
change_even_to_zero_advanced(input_array)

array([ 3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])